services:
  app:
    build: .
    ports:
      - "6565:6565"
      - "8080:8080"
      - "8000:8000"
    environment:
      - AB_CLIENT_ID=${AB_CLIENT_ID}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET}
      - AB_BASE_URL=${AB_BASE_URL}
      - AB_NAMESPACE=${AB_NAMESPACE}
      - BASE_PATH=${BASE_PATH}
      - PLUGIN_GRPC_SERVER_AUTH_ENABLED
      - DOCDB_HOST=${DOCDB_HOST}
      - DOCDB_USERNAME=${DOCDB_USERNAME}
      - DOCDB_PASSWORD=${DOCDB_PASSWORD}
      - DOCDB_DATABASE_NAME=${DOCDB_DATABASE_NAME}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans # Zipkin
      - OTEL_SERVICE_NAME=ExtendServiceExtensionServerGo
      # - GRPC_GO_LOG_VERBOSITY_LEVEL="99" # enable to debug grpc
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info # enable to debug grpc
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mongodb
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://host.docker.internal:3100/loki/api/v1/push
    #     mode: non-blocking
    #     max-buffer-size: 4m
    #     loki-retries: "3"
  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s